# -*- coding: utf-8 -*-
"""breast_cancer_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kgaglx91_fEFLTmq7lc_urV8J_rqSZGb
"""

"""
Breast Cancer Wisconsin Classifier with Cross-Validation
Author: [Your Name]
Date: 2026-05-26
Description: Binary classification of breast cancer tumors (benign vs malignant)
             using Logistic Regression, Decision Tree, and SVM with k-fold CV.
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

# Load and prepare dataset
def load_data():
    """Load the Breast Cancer Wisconsin dataset"""
    data = load_breast_cancer(as_frame=True)
    X = data.frame.drop(columns=['target'])
    y = data.frame['target']
    return X, y

# Split data
def split_data(X, y, test_size=0.2, random_state=42):
    """Split data into train and test sets with stratification"""
    return train_test_split(X, y, test_size=test_size, random_state=random_state, stratify=y)

# Main homework function
def homework(X_train, y_train, model_type, k):
    """
    Perform k-fold cross-validation with a pipeline containing
    StandardScaler and the specified classifier.
    """
    if model_type == 'logistic_regression':
        classifier = LogisticRegression(random_state=42, max_iter=1000)
    elif model_type == 'decision_tree':
        classifier = DecisionTreeClassifier(random_state=42)
    elif model_type == 'svm':
        classifier = SVC(random_state=42)
    else:
        raise ValueError("model_type must be 'logistic_regression', 'decision_tree', or 'svm'")

    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('classifier', classifier)
    ])

    scores = cross_val_score(pipeline, X_train, y_train, cv=k, scoring='accuracy')
    return float(scores.mean())

if __name__ == "__main__":
    print("Loading data...")
    X, y = load_data()
    X_train, X_test, y_train, y_test = split_data(X, y)

    print(f"Training set size: {X_train.shape}")
    print(f"Test set size: {X_test.shape}")

    print("\nModel Comparison (k=5):")
    print(f"Logistic Regression: {homework(X_train, y_train, 'logistic_regression', 5):.4f}")
    print(f"Decision Tree: {homework(X_train, y_train, 'decision_tree', 5):.4f}")
    print(f"SVM: {homework(X_train, y_train, 'svm', 5):.4f}")